### ISSUE TITLE
Develop api to create certificate

### ISSUE THREAD

**Issue by krishnakr6** [Tibil-vishwAAs/Vishwaas#10]
Create api - /certificates with POST method . Which accepts Certificate data and creates certificate using sunbird rc

Note: Follow the development principles of vishwaas.

**Comment by krishnakr6** [comment]
Create api - /certificates with POST method . Which accepts Certificate data and creates certificate using sunbird rc 
Note: Follow the development principles of vishwaas.

**Comment by Snegha-M** [comment]
Created endpoint as api/v1/Certificates checking whether the certificate already exists or not using get entity API if certificate already exists returning message as certificate exists or else creating new certificate using create entity API
PR link: https://github.com/Tibil-vishwAAs/Vishwaas/pull/6

Framework: Flask

**Comment by Pavan-tibil** [comment]
Created API end point /certificates and change the strings to constants where ever required.
PR link : [https://github.com/Tibil-vishwAAs/Vishwaas/pull/7]()

Framework used - Django-REST-Framework(4.0.3)

**Comment by Pavan-tibil** [comment]
need to add comments to every functions and need to create one class to handle the response code. Will work on it and complete it by tomorrow.

**Comment by Pavan-tibil** [comment]
commented for all the functions and classes and created a class to handle the responses. And completed all the chnages mentioned in issues. PR link - [https://github.com/Tibil-vishwAAs/Vishwaas/pull/7]()

**Comment by TaherKing** [comment]
Added .gitIgnore file and removed unused lines and files
[https://github.com/Tibil-vishwAAs/Vishwaas/pull/12](url)

**Comment by TaherKing** [comment]
Removed application file
[https://github.com/Tibil-vishwAAs/Vishwaas/pull/12](url)
