### ISSUE TITLE
Develop api for verification of created certificates

### ISSUE THREAD

**Issue by krishnakr6** [Tibil-vishwAAs/Vishwaas#11]
Create api - /Verification with GET method . Which accepts Certificate ID and Verifies the  certificate using sunbird rc

Note: Follow the development principles of vishwaas.

**Comment by krishnakr6** [comment]
@Pavan-tibil @Snegha-M @TaherKing Add the respective comments and PR links. 
Also mention the framework which you have used.

**Comment by Pavan-tibil** [comment]
Created the API for the verification of created certificate but the end-point name is create_certificate in this code, i will change it to /Verification. PR link - [https://github.com/Tibil-vishwAAs/Vishwaas/pull/7]().
Framework used - Django-REST-Framework(4.0.3)

**Comment by Snegha-M** [comment]
Created api/v1/Verification endpoint in get method by passing particular certificate ID and getting request body of that particular ID and escaping the osSignedData and passing that osSignedData as signedCredential for the API verify URL in post method 
PR link: https://github.com/Tibil-vishwAAs/Vishwaas/pull/6

Framework: Flask

**Comment by Pavan-tibil** [comment]
changed the API endpoint to /verification and change the strings to constants where ever required.
PR link : [https://github.com/Tibil-vishwAAs/Vishwaas/pull/7](url)

**Comment by TaherKing** [comment]
Created api/v1/Verification endpoint with get method by passing  certificate ID and getting request body of that particular ID and escaping the osSignedData and passing that osSignedData as signedCredential for the verify API  in post method and getting verified response.
PR link : https://github.com/Tibil-vishwAAs/Vishwaas/pull/12

**Comment by krishnakr6** [comment]
@TaherKing could you mention the Java and spring boot version

**Comment by Pavan-tibil** [comment]
commented for all the functions and classes and created a class to handle the responses. And completed all the chnages mentioned in issues. PR link - [https://github.com/Tibil-vishwAAs/Vishwaas/pull/7]()

**Comment by TaherKing** [comment]
> @TaherKing could you mention the Java and spring boot version
Added the java and spring boot version
