### ISSUE TITLE
Dockerize the existing portal backend API code.

### ISSUE THREAD

**Issue by krishnakr6** [Tibil-vishwAAs/Vishwaas#23]
Dockerize the existing portal backend API code, which has two APIs /certificates and /verification.

**Comment by AmithRangadhol04** [comment]
Pull request of the Dockerfile added in the portal-backend java code [https://github.com/Tibil-vishwAAs/Vishwaas/pull/32](url)

**Comment by krishnakr6** [comment]
completed
