### ISSUE TITLE
Learn and Understand Azure fundamentals

### ISSUE THREAD

**Issue by krishnakr6** [Tibil-vishwAAs/Vishwaas#24]
Learn and Understand Azure fundamentals using official Azure website https://learn.microsoft.com/en-us/certifications/exams/az-900/

**Comment by AmithRangadhol04** [comment]
I have understood the cloud, architecture and services, management and governance in the Azure fundamentals and created a document [https://docs.google.com/document/d/1neewRzJqNv6hNgnS_0HzkE6eBinQJbh6CgBeKeJ563k/edit?usp=sharing](url)

**Comment by TaherKing** [comment]
I have understood the Microsoft Azure fundamentals concepts are cloud,architecture and management and governance.

**Comment by krishnakr6** [comment]
> I have understood the cloud, architecture and services, management and governance in the Azure fundamentals and created a document [https://docs.google.com/document/d/1neewRzJqNv6hNgnS_0HzkE6eBinQJbh6CgBeKeJ563k/edit?usp=sharing](url)

@AmithRangadhol04 The url is not opening , could you check and update the working url

**Comment by AmithRangadhol04** [comment]
I have understood the cloud, architecture and services, management and governance in the Azure fundamentals and created a document [https://docs.google.com/document/d/1neewRzJqNv6hNgnS_0HzkE6eBinQJbh6CgBeKeJ563k/edit?usp=sharing](url)

**Comment by AmithRangadhol04** [comment]
> > I have understood the cloud, architecture and services, management and governance in the Azure fundamentals and created a document [https://docs.google.com/document/d/1neewRzJqNv6hNgnS_0HzkE6eBinQJbh6CgBeKeJ563k/edit?usp=sharing](url)
> 
> @AmithRangadhol04 The url is not opening , could you check and update the working url

@krishnakr6 Updated

**Comment by AmithRangadhol04** [comment]
I have understood the cloud, architecture and services, management and governance in the Azure fundamentals and created a updated document https://docs.google.com/document/d/1neewRzJqNv6hNgnS_0HzkE6eBinQJbh6CgBeKeJ563k/edit?usp=sharing
