### ISSUE TITLE
Store the details of certificate creation and verification in Azure Managed Postgres

### ISSUE THREAD

**Issue by krishnakr6** [Tibil-vishwAAs/Vishwaas#25]
Create two Tables
1. Certificate table to store the details of created certificates.
2. Verification table to store the details of verification.

**Comment by TaherKing** [comment]
- [ ] 1. Create a certificate table schema which consists all the required column name
- [ ] 2. create a verification table schema which consists all the required column name
- [ ] 3. download the postgresql  
- [ ] 4. write the java code for the table certificates and verification and connect it to postgresql and store the details of the both tables in postgresql.
- [ ] 5.Java code should support both local postgresql and azure managed postgresql database.

**Comment by krishnakr6** [comment]
code to store verification details in DB is been moved to todo .
@TaherKing
