### ISSUE TITLE
Deploy the docker images into kubernetes

### ISSUE THREAD

**Issue by krishnakr6** [Tibil-vishwAAs/Vishwaas#30]

**Comment by AmithRangadhol04** [comment]
- [ ] Build the code into the Docker Image.
- [ ] Verify that the Docker image is running successfully.
- [ ] Start the Minikube(Kubernetes) services.
- [ ] Create deployment and service scripts.
- [ ] Run and verify that scripts are deployed.
- [ ] Check that Pods are created based on our script.
- [ ] Verify whether the service is exposed in the browser or not.

**Comment by krishnakr6** [comment]
completed in local system
