### ISSUE TITLE
Explore and choose Test framework

### ISSUE THREAD

**Issue by krishnakr6** [Tibil-vishwAAs/Vishwaas#40]

**Comment by Andolepriti** [comment]
I finished the framework document you can closed this issue

**Comment by krishnakr6** [comment]
@Andolepriti Add the document link here.

**Comment by Andolepriti** [comment]
- [ ] https://docs.google.com/document/d/1GgNNNl0NyAduPikpZr8BDSMexCMhWljnakQx1AGPviw/edit
